/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.insarouen.asi.dressing.frames;

import fr.insarouen.asi.dressing.Initialisation;
import fr.insarouen.asi.dressing.elements.Couleur;
import fr.insarouen.asi.dressing.elements.CouleurCheveux;
import fr.insarouen.asi.dressing.elements.Signe;
import fr.insarouen.asi.dressing.elements.utilisateurs.Utilisateur;
import java.awt.CardLayout;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pauline
 */
public class InitFrame extends javax.swing.JFrame {

    /**
     * Creates new form InitFrame
     */
    public InitFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox3 = new javax.swing.JComboBox();
        MainFrame = new javax.swing.JPanel();
        premiereConnexion = new javax.swing.JButton();
        Connexion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomBase = new javax.swing.JTextField();
        nomUtilisateur = new javax.swing.JTextField();
        connecter = new javax.swing.JButton();
        Accueil = new javax.swing.JPanel();
        accesDressing = new javax.swing.JButton();
        ajoutUtilisateur = new javax.swing.JButton();
        supprUtilisateur = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idUtilisateur = new javax.swing.JTextField();
        identifiant = new javax.swing.JLabel();
        idSuppr = new javax.swing.JTextField();
        ConsulterDressing = new javax.swing.JPanel();
        AccueilDressing = new javax.swing.JPanel();
        dressing = new javax.swing.JButton();
        corebeille = new javax.swing.JButton();
        creerTenue = new javax.swing.JButton();
        age = new javax.swing.JLabel();
        taille = new javax.swing.JLabel();
        coulCheveux = new javax.swing.JLabel();
        coulPreferee = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        AjoutUtilisateur = new javax.swing.JPanel();
        nouveauNom = new javax.swing.JTextField();
        nouveauPrenom = new javax.swing.JTextField();
        nouveauAge = new javax.swing.JTextField();
        nouveauTaille = new javax.swing.JTextField();
        jScrollBar1 = new javax.swing.JScrollBar();
        nouveauCoulC = new javax.swing.JComboBox();
        nouveauCoulP = new javax.swing.JComboBox();
        nouveauSigne = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        validerAjoutUtilisateur = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainFrame.setLayout(new java.awt.CardLayout());

        premiereConnexion.setText("Se connecter");
        premiereConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                premiereConnexionActionPerformed(evt);
            }
        });
        MainFrame.add(premiereConnexion, "card2");

        jLabel2.setText("Base :");

        jLabel3.setText("Utilisateur :");

        connecter.setText("Se connecter");
        connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connecterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConnexionLayout = new javax.swing.GroupLayout(Connexion);
        Connexion.setLayout(ConnexionLayout);
        ConnexionLayout.setHorizontalGroup(
            ConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConnexionLayout.createSequentialGroup()
                .addGroup(ConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConnexionLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(ConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ConnexionLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(43, 43, 43)
                                .addComponent(nomUtilisateur))
                            .addGroup(ConnexionLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(80, 80, 80)
                                .addComponent(nomBase, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ConnexionLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(connecter)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        ConnexionLayout.setVerticalGroup(
            ConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConnexionLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(ConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(ConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(connecter)
                .addGap(44, 44, 44))
        );

        MainFrame.add(Connexion, "Connexion");

        accesDressing.setText("Acceder à votre dressing");
        accesDressing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesDressingActionPerformed(evt);
            }
        });

        ajoutUtilisateur.setText("Ajouter un utilisateur");
        ajoutUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutUtilisateurActionPerformed(evt);
            }
        });

        supprUtilisateur.setText("Supprimer un utilisateur");
        supprUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprUtilisateurActionPerformed(evt);
            }
        });

        jLabel4.setText("Identifiant :");

        identifiant.setText("Identifiant :");

        javax.swing.GroupLayout AccueilLayout = new javax.swing.GroupLayout(Accueil);
        Accueil.setLayout(AccueilLayout);
        AccueilLayout.setHorizontalGroup(
            AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccueilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AccueilLayout.createSequentialGroup()
                        .addComponent(identifiant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idSuppr)
                        .addGap(18, 18, 18)
                        .addComponent(supprUtilisateur))
                    .addGroup(AccueilLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(accesDressing)))
                .addGap(20, 20, 20))
            .addGroup(AccueilLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(ajoutUtilisateur)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AccueilLayout.setVerticalGroup(
            AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccueilLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accesDressing))
                .addGap(45, 45, 45)
                .addGroup(AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supprUtilisateur)
                    .addComponent(identifiant)
                    .addComponent(idSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(ajoutUtilisateur)
                .addGap(35, 35, 35))
        );

        MainFrame.add(Accueil, "Accueil");

        javax.swing.GroupLayout ConsulterDressingLayout = new javax.swing.GroupLayout(ConsulterDressing);
        ConsulterDressing.setLayout(ConsulterDressingLayout);
        ConsulterDressingLayout.setHorizontalGroup(
            ConsulterDressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        ConsulterDressingLayout.setVerticalGroup(
            ConsulterDressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        MainFrame.add(ConsulterDressing, "ConsulterDressing");

        dressing.setText("Dressing");
        dressing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dressingActionPerformed(evt);
            }
        });

        corebeille.setText("Corbeille à linge");

        creerTenue.setText("Créer une tenue");

        age.setText("age");

        taille.setText("taille");

        coulCheveux.setText("couleur Cheveux");

        coulPreferee.setText("couleur Préférée");

        jLabel1.setText("Nos Conseils :");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout AccueilDressingLayout = new javax.swing.GroupLayout(AccueilDressing);
        AccueilDressing.setLayout(AccueilDressingLayout);
        AccueilDressingLayout.setHorizontalGroup(
            AccueilDressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccueilDressingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccueilDressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dressing)
                    .addComponent(corebeille)
                    .addComponent(creerTenue))
                .addGap(19, 19, 19)
                .addGroup(AccueilDressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccueilDressingLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(159, 159, 159))
                    .addGroup(AccueilDressingLayout.createSequentialGroup()
                        .addGroup(AccueilDressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AccueilDressingLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(AccueilDressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AccueilDressingLayout.createSequentialGroup()
                                        .addComponent(age)
                                        .addGap(18, 18, 18)
                                        .addComponent(coulCheveux))
                                    .addGroup(AccueilDressingLayout.createSequentialGroup()
                                        .addComponent(taille)
                                        .addGap(18, 18, 18)
                                        .addComponent(coulPreferee))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        AccueilDressingLayout.setVerticalGroup(
            AccueilDressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccueilDressingLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(AccueilDressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(coulCheveux)
                    .addComponent(dressing))
                .addGroup(AccueilDressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccueilDressingLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(AccueilDressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taille)
                            .addComponent(coulPreferee))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(AccueilDressingLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(corebeille)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AccueilDressingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addGroup(AccueilDressingLayout.createSequentialGroup()
                        .addComponent(creerTenue)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        MainFrame.add(AccueilDressing, "AccueilDressing");

        nouveauCoulC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blond", "Brun", "Roux", "Chatain" }));
        nouveauCoulC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveauCoulCActionPerformed(evt);
            }
        });

        nouveauCoulP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bleu", "Bleu clair", "Bleu marine", "Turquoise", "Gris clair", "Argenté", "Gris foncé", "Marron clair", "Marron foncé", "Corail", "Orange", "Bordeau", "Brique", "Rouge", "Rose pale", "Rose fushia", "Rose foncé", "Mauve", "Violet", "Prune", "Blanc", "Jaune moutarde ", "Jaune", "Doré", "Noir", "Kaki", "Vert pale", "Vert", "Jean clair", "Jean marine", "Beige" }));
        nouveauCoulP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveauCoulPActionPerformed(evt);
            }
        });

        nouveauSigne.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "V", "O", "H", "A", "X" }));

        jLabel5.setText("nom :");

        jLabel6.setText("prénom :");

        jLabel7.setText("âge :");

        jLabel8.setText("taille :");

        jLabel9.setText("couleur cheveux :");

        jLabel10.setText("couleur préférée :");

        jLabel11.setText("Signe :");

        validerAjoutUtilisateur.setText("Valider");
        validerAjoutUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerAjoutUtilisateurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AjoutUtilisateurLayout = new javax.swing.GroupLayout(AjoutUtilisateur);
        AjoutUtilisateur.setLayout(AjoutUtilisateurLayout);
        AjoutUtilisateurLayout.setHorizontalGroup(
            AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjoutUtilisateurLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nouveauCoulP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nouveauSigne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validerAjoutUtilisateur)
                    .addGroup(AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nouveauTaille, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nouveauAge, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nouveauPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nouveauNom, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nouveauCoulC, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(123, 123, 123)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        AjoutUtilisateurLayout.setVerticalGroup(
            AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjoutUtilisateurLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nouveauNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nouveauPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nouveauAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nouveauTaille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nouveauCoulC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nouveauCoulP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(AjoutUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nouveauSigne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(33, 33, 33)
                .addComponent(validerAjoutUtilisateur)
                .addContainerGap(55, Short.MAX_VALUE))
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MainFrame.add(AjoutUtilisateur, "AjoutUtilisateur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void premiereConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_premiereConnexionActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainFrame.getLayout();
        card.show(MainFrame, "Connexion");
    }//GEN-LAST:event_premiereConnexionActionPerformed

    private void connecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connecterActionPerformed
        // TODO add your handling code here:
        Boolean connecte = Initialisation.connexion(nomUtilisateur.getText(), nomBase.getText());
        if (connecte) {
            CardLayout card = (CardLayout) MainFrame.getLayout();
            card.show(MainFrame, "Accueil");
        }
        else {
            CardLayout card = (CardLayout) MainFrame.getLayout();
            card.show(MainFrame, "Connexion");
        }
    }//GEN-LAST:event_connecterActionPerformed

    private void accesDressingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesDressingActionPerformed

        CardLayout card = (CardLayout) MainFrame.getLayout();
        card.show(MainFrame, "AccueilDressing");

        try {

            // TODO add your handling code here:
            Utilisateur user = Initialisation.accederDressing(Integer.parseInt(idUtilisateur.getText()));
            //  if (user ){
            //Ne fonctionne pas, je nesais pas pourquoi ...
            age.setText(Integer.toString(user.getAge()));
            taille.setText(Integer.toString(user.getTaille()));
            //coulPreferee.setText(Integer.toString(user.getCouleurPreferee().getCouleur()));
            //   }

        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_accesDressingActionPerformed

    private void supprUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprUtilisateurActionPerformed
        // TODO add your handling code here:
        Utilisateur user = new Utilisateur();
        try {
            boolean buser = user.supprimerUtilisateur(Integer.parseInt(idSuppr.getText()));
            
            // boite de dialogue : 
            JOptionPane jop1 = new JOptionPane();
            jop1.showMessageDialog(Accueil, "Utilisateur supprimé !", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        } catch (SQLException ex) {
            Logger.getLogger(InitFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_supprUtilisateurActionPerformed

    private void nouveauCoulPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauCoulPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nouveauCoulPActionPerformed

    private void validerAjoutUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerAjoutUtilisateurActionPerformed
        // TODO add your handling code here:
        
        Utilisateur user = new Utilisateur();
        try {
            boolean buser = user.ajouterUtilisateur(nouveauNom.getText(),nouveauPrenom.getText(),Integer.parseInt(nouveauAge.getText()), Integer.parseInt(nouveauTaille.getText()), CouleurCheveux.get((String)nouveauCoulC.getSelectedItem()),new Couleur(nouveauCoulP.getSelectedIndex()+1),Signe.getfromInt(nouveauSigne.getSelectedIndex()+1));
            int id = user.getId();
            JOptionPane jop1 = new JOptionPane();
            jop1.showMessageDialog(AjoutUtilisateur, "Utilisateur ajouté ! \n Votre identifiant est : "+id, "Information", JOptionPane.INFORMATION_MESSAGE);
            
            CardLayout card = (CardLayout) MainFrame.getLayout();
            card.show(MainFrame, "Accueil");
        } catch (SQLException ex) {
            Logger.getLogger(InitFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_validerAjoutUtilisateurActionPerformed

    private void dressingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dressingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dressingActionPerformed

    private void nouveauCoulCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauCoulCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nouveauCoulCActionPerformed

    private void ajoutUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutUtilisateurActionPerformed
       // TODO add your handling code here:
        CardLayout card = (CardLayout) MainFrame.getLayout();
        card.show(MainFrame, "AjoutUtilisateur");
    }//GEN-LAST:event_ajoutUtilisateurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new InitFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accueil;
    private javax.swing.JPanel AccueilDressing;
    private javax.swing.JPanel AjoutUtilisateur;
    private javax.swing.JPanel Connexion;
    private javax.swing.JPanel ConsulterDressing;
    private javax.swing.JPanel MainFrame;
    private javax.swing.JButton accesDressing;
    private javax.swing.JLabel age;
    private javax.swing.JButton ajoutUtilisateur;
    private javax.swing.JButton connecter;
    private javax.swing.JButton corebeille;
    private javax.swing.JLabel coulCheveux;
    private javax.swing.JLabel coulPreferee;
    private javax.swing.JButton creerTenue;
    private javax.swing.JButton dressing;
    private javax.swing.JTextField idSuppr;
    private javax.swing.JTextField idUtilisateur;
    private javax.swing.JLabel identifiant;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField nomBase;
    private javax.swing.JTextField nomUtilisateur;
    private javax.swing.JTextField nouveauAge;
    private javax.swing.JComboBox nouveauCoulC;
    private javax.swing.JComboBox nouveauCoulP;
    private javax.swing.JTextField nouveauNom;
    private javax.swing.JTextField nouveauPrenom;
    private javax.swing.JComboBox nouveauSigne;
    private javax.swing.JTextField nouveauTaille;
    private javax.swing.JButton premiereConnexion;
    private javax.swing.JButton supprUtilisateur;
    private javax.swing.JLabel taille;
    private javax.swing.JButton validerAjoutUtilisateur;
    // End of variables declaration//GEN-END:variables

    private void setContentPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
